### ISSUE TITLE
How to use elastic-mock properly?

### ISSUE THREAD

**Issue by Artem-Tsymbal** [elastic/elasticsearch-js-mock#26]
"@elastic/elasticsearch": "^8.1.0",
"@elastic/elasticsearch-mock": "^2.0.0",
 "jest": "^24.9.0",
  Node: v12.22.7

<img width="496" alt="image" src="https://user-images.githubusercontent.com/46108437/164009796-b71aace9-3e79-4bdd-a4f5-10720998d1d6.png">

console.log(mock.getConnection()) -> [class MockConnection extends BaseConnection]

  ```
console.error node_modules/jest-jasmine2/build/jasmine/Env.js:289
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:290
    ResponseError: {"error":"Mock not found"}
        at SniffingTransport.request (.../node_modules/@elastic/transport/src/Transport.ts:532:17)
        at Indices.delete (.../node_modules/@elastic/elasticsearch/src/api/api/indices.ts:301:12)
```

**Comment by Artem-Tsymbal** [comment]
Hello, could anybody help me to solve my error

**Comment by XOlvl9lK** [comment]
I have the same problem {"error":"Mock not found"}

**Comment by wangdrew** [comment]
I also got `{"error":"Mock not found"}` because the mock received a request that doesn't match any resolver function that I set up. In my case, I didn't pay close attention to the fact that my application code was hitting ElasticSearch with a POST request and I had set up the mock resolver with `method: 'GET'` like in the code examples.

**Comment by dimas-cyriaco** [comment]
It would be nice for this error to show what request was made. This way we could more easily create the correct handler.

**Comment by JoshMock** [comment]
Request parameters have been added to the "mock not found" error response body. v2.1.0 has been published with the improvement.
